import { PLANNER_FACTORS } from '../lib/plannerState.js'

const number = value => Number.isFinite(value) ? value.toFixed(1) : 'Unknown'
const delta = value => Number.isFinite(value) ? `${value > 0 ? '+' : ''}${value.toFixed(2)}` : 'Excluded'
const name = id => PLANNER_FACTORS.find(f => f.id === id)?.short || id
const winnerName = winner => winner === 'tie' ? 'a tie' : winner ? `option ${winner}` : 'no eligible option'

export default function RecommendationAudit({ result, proposed, options }) {
  const audit = result.audit
  if (!audit) return null
  const state = proposed ? 'proposal' : 'baseline', sensitivity = audit.sensitivity[state]
  const drivers = [...audit.factors].filter(f => f.included && Math.abs(f.gaps[state]) > .000001).sort((a, b) => Math.abs(b.gaps[state]) - Math.abs(a.gaps[state]))
  return <section className="recommendation-audit" aria-label="Recommendation evidence">
    <div className="section-heading"><h3>Why this result?</h3><span className="data-badge">Traceable</span></div>
    <p className="section-help">Both housing options are tested against the same infrastructure change. Shared access gains can raise both scores without changing which housing option leads.</p>
    <details className="planner-details" open><summary>What changed with infrastructure?</summary><div className="audit-table-wrap"><table className="audit-table"><caption>Contribution to each total score, proposal minus baseline</caption><thead><tr><th>Factor</th><th>A Δ</th><th>B Δ</th></tr></thead><tbody>{audit.factors.map(f => <tr key={f.id}><th>{f.short}</th><td>{delta(f.values.A.weightedDelta)}</td><td>{delta(f.values.B.weightedDelta)}</td></tr>)}</tbody></table></div><p>Zero means no modeled change. Excluded means missing evidence or zero priority. This comparison holds housing choices and affordability inputs constant.</p>{audit.factors.map(f => <details key={f.id} className="audit-factor"><summary>{f.short} · {f.included ? `${(f.effectiveWeight * 100).toFixed(1)}% effective weight` : 'Excluded'}</summary><p>{f.effect}</p><p>A: {number(f.values.A.before)} → {number(f.values.A.after)}; B: {number(f.values.B.before)} → {number(f.values.B.after)} / 100.</p>{f.exclusion && <p>{f.exclusion}</p>}<small>Source: {f.source}</small></details>)}</details>
    <details className="planner-details" open><summary>What separates A and B?</summary><p>{proposed ? 'Proposal' : 'Baseline'} score points: positive favors A, negative favors B. Contributions add to the unrounded A−B score gap; eligibility is checked separately.</p>{drivers.length ? <ul className="audit-drivers">{drivers.map(f => <li key={f.id}><span>{f.label}</span><strong>{delta(f.gaps[state])}</strong></li>)}</ul> : <p>No weighted factor separates the two options.</p>}<div className="audit-gates">{['A', 'B'].map(slot => <p key={slot}><strong>{slot} · {options[slot].eligible ? 'Screen passed' : 'Review required'}</strong><span>{options[slot].gate}</span></p>)}</div></details>
    <details className="planner-details"><summary>Does the lead depend on priorities?</summary>{!sensitivity.applicable ? <p>Weight sensitivity needs two eligible housing options and at least one weighted factor. Resolve the review gates first.</p> : <><p>Vary each included priority by −25% and +25%, one at a time, while keeping inputs and coverage fixed. This is a preference check, not a confidence interval or model validation.</p><strong>{sensitivity.changedCases.length ? `${sensitivity.changedCases.length} of ${sensitivity.cases.length} checks change the result.` : `Same result in all ${sensitivity.cases.length} checks.`}</strong>{sensitivity.changedCases.length > 0 && <ul>{sensitivity.changedCases.map(c => <li key={`${c.factor}-${c.multiplier}`}>{name(c.factor)} weight {c.multiplier < 1 ? '−25%' : '+25%'} → {winnerName(c.winner)}</li>)}</ul>}</>}</details>
    <details className="planner-details"><summary>Evidence gaps & feasibility review</summary><p>Passing the outline and use screen does not establish that a development can be built. Hazard overlaps below are review flags, not project-specific engineering findings.</p><ul>{audit.hazards.map(h => <li key={h.id}>{h.label}: {h.overlap === null ? 'unknown — needs review' : `${(h.overlap * 100).toFixed(1)}% overlap${h.review ? ' — needs review' : ' in this source'}`}</li>)}</ul><strong>Still unreviewed</strong><ul>{audit.unreviewed.map(note => <li key={note}>{note}</li>)}</ul>{audit.sourceNotes.length > 0 && <><strong>Source caveats for this parcel</strong><ul>{audit.sourceNotes.map(note => <li key={note}>{note}</li>)}</ul></>}</details>
  </section>
}
